# Generated by Django 3.1.5 on 2021-01-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descriptions',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
